# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 195a4ed91ee06f421e2c3ebb4c3a6f4ea2bbf59fdc3a38075d74bf922eb421252ad72d3f1d73def6f0f6b6210eb7c05fd5767908dfd50b8dc2c726d7d4de9eb7

test:
  secret_key_base: dd4b5534028a7f68e2149d9d5e200ba972030129864f4d95e66ac28ec6908975c2dc322f4a2e387109d73d58d4c4bd64c37383a4fbc8666038486986c02acb04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
